fix: disable MonoLocalBinds
    src/ShellCheck/CFGAnalysis.hs:624:14: error: [GHC-83865]
        • Couldn't match type ‘S.Set FunctionDefinition’
                         with ‘VariableState’
          Expected: InternalState -> VersionedMap String VariableState
            Actual: InternalState -> VersionedMap String FunctionValue
        • In the first argument of ‘check’, namely ‘sFunctionTargets’
          In the first argument of ‘(&&)’, namely ‘check sFunctionTargets’
          In the second argument of ‘(&&)’, namely
            ‘check sFunctionTargets && check sIsReachable’
        |
    624 |     && check sFunctionTargets
        |              ^^^^^^^^^^^^^^^^

    src/ShellCheck/CFGAnalysis.hs:625:14: error: [GHC-83865]
        • Couldn't match type: Maybe Bool
                         with: VersionedMap String VariableState
          Expected: InternalState -> VersionedMap String VariableState
            Actual: InternalState -> Maybe Bool
        • In the first argument of ‘check’, namely ‘sIsReachable’
          In the second argument of ‘(&&)’, namely ‘check sIsReachable’
          In the second argument of ‘(&&)’, namely
            ‘check sFunctionTargets && check sIsReachable’
        |
    625 |     && check sIsReachable
        |              ^^^^^^^^^^^^

    src/ShellCheck/CFGAnalysis.hs:1334:17: error: [GHC-46956]
        • Couldn't match type ‘s0’ with ‘s’
          Expected: ST s CFGAnalysis
            Actual: ST s0 CFGAnalysis
            because type variable ‘s’ would escape its scope
          This (rigid, skolem) type variable is bound by
            a type expected by the context:
              forall s. ST s CFGAnalysis
            at src/ShellCheck/CFGAnalysis.hs:1334:17-32
        • In the second argument of ‘($)’, namely ‘f cfg entry exit’
          In the expression: runST $ f cfg entry exit
          In the expression:
            let
              cfg = buildGraph params t
              (entry, exit)
                = M.findWithDefault
                    (error $ pleaseReport "Missing root") (getId t) (cfIdToRange cfg)
            in runST $ f cfg entry exit
        • Relevant bindings include
            f :: CFGResult -> Node -> Node -> ST s0 CFGAnalysis
              (bound at src/ShellCheck/CFGAnalysis.hs:1336:5)
         |
    1334 |         runST $ f cfg entry exit
         |                 ^^^^^^^^^^^^^^^^